spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/database
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

kafka:
  bootstrap-servers: host.docker.internal:9092
  topic:
    product-events:
      partitions: 3
      replication-factor: 1

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

